services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 60s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8001:80"
    volumes:
      - ./frontend:/app
      - ./config:/app/config
    environment:
      - WS_URL=ws://backend:8000/audio
      - GRADIO_SERVER_NAME=0.0.0.0
    depends_on:
      backend:
        condition: service_healthy
